backend = "glx";
glx-copy-from-front = false;

corner-radius = 10;
rounded-corners-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'"
];

shadow = true;
shadow-radius = 15;
shadow-offset-x = -15;
shadow-offset-y = -15;
shadow-opacity = 0.5;
shadow-exclude = [
  "name = 'Notification'",
  "class_g = 'Polybar'",
  "_GTK_FRAME_EXTENTS@:c"
];

fading = true;
fade-delta = 5;
fade-in-step = 0.06;
fade-out-step = 0.06;

blur-method = "dual_kawase";
blur-strength = 5;
blur-background = true;
blur-background-frame = true;
blur-background-fixed = true;

blur-background-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "_GTK_FRAME_EXTENTS@:c"
];

opacity-rule = [
  "85:class_g = 'Code'",
  "85:class_g = 'vesktop'",
  "75:class_g = 'Spotify'",
  "85:class_g = 'Thunar'"
# "90:class_g = 'Microsoft-edge'"
];
